### ISSUE TITLE
Windows specific requirement

### ISSUE THREAD

**Issue by mchalela** [carosaav/SimulAI#27]
https://github.com/carosaav/SimulAI/blob/cc9fa6f39ed5bae4e9522d1f47fa3b7faab0458c/setup.py#L37

If you add pywin32 as a requirement in your setup.py, travis will fail because it tests in a linux platform.
Two options:
1 -  You don't add it to the setup.py and then ask the user to install it.
2 - You can check the platform and if it is windows then add it to your requirements. Something like this:

```python
import sys

REQUIREMENTS = ["numpy", "attrs"]
 
# Install pywin32 if OS is Windows.
if sys.platform.startswith("win"):
    REQUIREMENTS.append("pywin32")
```

**Comment by carosaav** [comment]
I tried solution 2 but it didn't work so I leave solution 1.
